import { getProductImageUrl } from "../utils/imageLoader";

export const products = [
  // --- DRESSES (1–6) ---
  {
    id: 1,
    name: "Satin Cowl Neck Midi Slip Dress",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-01-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-01-01.jpg"),
      getProductImageUrl("Dresses", "product-01-02.jpg"),
      getProductImageUrl("Dresses", "product-01-03.jpg")
    ],
    price: 2499,
    originalPrice: 3499,
    rating: 4.9,
    reviews: 142,
    badge: "Bestseller",
    isNewArrival: false,
    isTrending: true,
    isBestSeller: true,
    isFeatured: true,
    description: "Crafted from liquid-drape satin on the bias, featuring an elegant cowl neckline and delicate adjustable rouleau straps[cite: 7].",
    brand: "Maison Aura",
    sku: "MA-DR-01",
    stock: 14,
    colors: ["Champagne", "Emerald Green", "Obsidian Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    specifications: { "Fabric": "Polyester Satin", "Fit": "Bias Cut", "Length": "Midi", "Care": "Dry Clean" }
  },
  {
    id: 2,
    name: "Tiered Cotton Voile Maxi Dress",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-02-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-02-01.jpg"),
      getProductImageUrl("Dresses", "product-02-02.jpg"),
      getProductImageUrl("Dresses", "product-02-03.jpg")
    ],
    price: 2999,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 98,
    badge: "New",
    isNewArrival: true,
    isTrending: true,
    isBestSeller: false,
    isFeatured: true,
    description: "Lightweight pure cotton voile dress with voluminous tiered ruffles, bishop sleeves, and a removable waist belt[cite: 7].",
    brand: "Maison Aura",
    sku: "MA-DR-02",
    stock: 20,
    colors: ["Soft Ivory", "Dusty Rose"],
    sizes: ["S", "M", "L", "XL"],
    specifications: { "Fabric": "100% Organic Cotton", "Fit": "Relaxed Tiered", "Care": "Machine Wash Gentle" }
  },
  {
    id: 3,
    name: "Pleated Halter-Neck Evening Gown",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-03-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-03-01.jpg"),
      getProductImageUrl("Dresses", "product-03-02.jpg"),
      getProductImageUrl("Dresses", "product-03-03.jpg")
    ],
    price: 3899,
    originalPrice: 4999,
    rating: 4.9,
    reviews: 64,
    badge: "Exclusive",
    isNewArrival: true,
    isTrending: true,
    isBestSeller: false,
    isFeatured: false,
    description: "Striking micro-pleated georgette gown featuring an open architectural back and an elongated neck-tie drape[cite: 7].",
    brand: "Maison Aura Atelier",
    sku: "MA-DR-03",
    stock: 8,
    colors: ["Burgundy Noir", "Champagne Gold"],
    sizes: ["XS", "S", "M", "L"],
    specifications: { "Fabric": "Micro-Pleated Georgette", "Care": "Dry Clean" }
  },
  {
    id: 4,
    name: "Linen Trench Button-Down Dress",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-04-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-04-01.jpg"),
      getProductImageUrl("Dresses", "product-04-02.jpg"),
      getProductImageUrl("Dresses", "product-04-03.jpg")
    ],
    price: 3299,
    originalPrice: 4299,
    rating: 4.7,
    reviews: 82,
    badge: "",
    isNewArrival: false,
    isTrending: false,
    isBestSeller: true,
    isFeatured: false,
    description: "Structured tailoring meets breezy Mediterranean linen with horn buttons and notched lapels[cite: 7].",
    brand: "Maison Aura",
    sku: "MA-DR-04",
    stock: 12,
    colors: ["Oatmeal", "Khaki Olive"],
    sizes: ["S", "M", "L"],
    specifications: { "Fabric": "100% French Flax Linen", "Care": "Hand Wash" }
  },
  {
    id: 5,
    name: "Square Neck Puff Sleeve Mini Dress",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-05-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-05-01.jpg"),
      getProductImageUrl("Dresses", "product-05-02.jpg"),
      getProductImageUrl("Dresses", "product-05-03.jpg")
    ],
    price: 1999,
    originalPrice: 2799,
    rating: 4.6,
    reviews: 110,
    badge: "Sale",
    isNewArrival: false,
    isTrending: true,
    isBestSeller: false,
    isFeatured: false,
    description: "Playful romanticism cut in crisp cotton poplin with elasticated puff sleeves and a smocked back bodice[cite: 7].",
    brand: "Aura Essentials",
    sku: "AE-DR-05",
    stock: 25,
    colors: ["Sage Green", "White"],
    sizes: ["XS", "S", "M", "L"],
    specifications: { "Fabric": "100% Cotton Poplin", "Care": "Machine Wash" }
  },
  {
    id: 6,
    name: "Cut-Out Ribbed Knit Column Dress",
    category: "Dresses",
    image: getProductImageUrl("Dresses", "product-06-01.jpg"),
    images: [
      getProductImageUrl("Dresses", "product-06-01.jpg"),
      getProductImageUrl("Dresses", "product-06-02.jpg"),
      getProductImageUrl("Dresses", "product-06-03.jpg")
    ],
    price: 2699,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 76,
    badge: "New",
    isNewArrival: true,
    isTrending: false,
    isBestSeller: false,
    isFeatured: false,
    description: "Seamless column silhouette sculpted from rich modal knit with a subtle asymmetrical waist cut-out[cite: 7].",
    brand: "Maison Aura",
    sku: "MA-DR-06",
    stock: 16,
    colors: ["Warm Espresso", "Charcoal Black"],
    sizes: ["S", "M", "L"],
    specifications: { "Fabric": "Modal Viscose", "Care": "Dry Flat" }
  }
];